### ISSUE TITLE
请问怎么做二级菜单？

### ISSUE THREAD

**Issue by ssssssbn** [gzhu2016/week12#7]
如点击一个按钮后，可以在最上层画出一个矩形，然后矩形里有其它按钮的菜单，用于放游戏选项的设置。谢谢。

**Comment by airingursb** [comment]
可以用一个做一个层外加一些按钮包装成组件。
点击按钮的时候弹出（显示）这个div层，这个div层里面有一些button，点击其他地方的时候div层消失
